sudo: required
language: cpp
osx_image: xcode10.1

before_install:
  - export CI_TRAVIS_SCRIPT_BASE_PATH="./ci/travis/$TRAVIS_OS_NAME"
install:
  - "$CI_TRAVIS_SCRIPT_BASE_PATH/setup.sh"
script:
  - "$CI_TRAVIS_SCRIPT_BASE_PATH/build.sh"
  - travis_wait 60 "$CI_TRAVIS_SCRIPT_BASE_PATH/run_unit_tests.sh"

matrix:
  include:
    - os: linux
      addons:
        apt: &gcc7
          sources:
            - ubuntu-toolchain-r-test
          sourceline:
            - 'deb http://cz.archive.ubuntu.com/ubuntu bionic main universe'
          packages:
            - g++-7
            - libasound2-dev
            - build-essential
      env: TRAVIS_CONFIGURATION_NAME=Debug
    - os: linux
      addons:
        apt: *gcc7
      env: TRAVIS_CONFIGURATION_NAME=Release

    - os: osx
      env: TRAVIS_CONFIGURATION_NAME=Debug

    - os: osx
      env: TRAVIS_CONFIGURATION_NAME=Release

    - os: osx
      env: TRAVIS_CONFIGURATION_NAME=USan

    - os: osx
      env: TRAVIS_CONFIGURATION_NAME=ASan

    - os: osx
      env: TRAVIS_CONFIGURATION_NAME=TSan