sudo: required
language: cpp
os: osx

before_install:
  - export CI_TRAVIS_SCRIPT_BASE_PATH="./ci/travis/$TRAVIS_OS_NAME"
  - eval "${SETUP_COMPILERS}"
script:
  - "$CI_TRAVIS_SCRIPT_BASE_PATH/build_and_test.sh"

matrix:
  include:
    - os: linux
      addons:
        apt: &gcc7
          sources:
            - ubuntu-toolchain-r-test
          sourceline:
            - 'deb http://cz.archive.ubuntu.com/ubuntu bionic main universe'
          packages:
            - g++-7
            - libasound2-dev
            - build-essential
            - qt5-default
            - qttools5-dev
      env: SETUP_COMPILERS="CC=gcc-7 && CXX=g++-7" TRAVIS_CONFIGURATION_NAME=Debug
    - os: linux
      addons:
        apt: *gcc7
      env: SETUP_COMPILERS="CC=gcc-7 && CXX=g++-7" TRAVIS_CONFIGURATION_NAME=Release

    - os: linux
      addons:
        apt: *gcc7
      env: SETUP_COMPILERS="CC=gcc-7 && CXX=g++-7" TRAVIS_CONFIGURATION_NAME=Retail

    - os: osx
      env: SETUP_COMPILERS="CC=clang CXX=clang++" TRAVIS_CONFIGURATION_NAME=Debug

    - os: osx
      env: SETUP_COMPILERS="CC=clang CXX=clang++" TRAVIS_CONFIGURATION_NAME=Release

    - os: osx
      env: SETUP_COMPILERS="CC=clang CXX=clang++" TRAVIS_CONFIGURATION_NAME=Retail
